### ISSUE TITLE
Backend port in nginx configuration is wrong

### ISSUE THREAD

**Issue by danieldiazastudillo** [dupinder/NgnixDockerizedDevEnv#1]
@dupinder Hi! Great work with this repo, it's very on-point and helps to understand some stuff about docker-compose and routing.

I think this is wrong:
```
# In our case Container name is as we setup in docker-compose `beservice` and port 8080
proxy_pass http://beservice:8080;
```

Why? Because the exposed port in docker-compose for `backend` it's `9002`:
```yml
ports:
      - 9002:8080 # App access Port, inside container it is 8080 and mappped with 9002
```

**Comment by dupinder** [comment]
`9002` port is mapping to the outside world, to access the backend application to outsides the docker container. 
in Simple words, inside docker container: port 8080 is used to access application, but to use application in browser or postman use 9002 port
