### ISSUE TITLE
What should I use as backend url in environment ?

### ISSUE THREAD

**Issue by danieldiazastudillo** [dupinder/NgnixDockerizedDevEnv#2]
Looking in `nginx.conf` some things are very clear:

>Let's assume that production server IP it's **555.666.777.88**

1. The default port for server IP will be port  `80`. So as I enter `http://555.666.777.88` will redirect me to the `ui-app`. Nice.
2. The `/backend` route will redirect me to `http://beservice:8080`. Now, if i send a request to `http://555.666.777.88/backend` the `nginx` configuration will redirect me to the corresponding `backend`container. Also pretty nice.

Here's my question. What's the URL to use in `environment` variable so the `ui-app` services can create the correct URL?

What should I use to avoid this approach of hardcoding the server IP...
```js
export const environment = {
  production: true,
  baseUrl: 'http://555.666.777.88:8080'
};
```

**Comment by dupinder** [comment]
I think yo u should not hard core the URL, Let the Docker decide the URL in side the container.

**Comment by dupinder** [comment]
closing
